# Generated by Django 4.2.1 on 2023-06-01 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('content', models.CharField(verbose_name=100, max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[
                 (1, 'Created'), (1, 'Delivered'), (1, 'Read')], default=1)),
                ('url', models.URLField(blank=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
