# Generated by Django 4.2.1 on 2023-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Delivered'), (3, 'Read')], default=1),
        ),
    ]
