# Generated by Django 4.1 on 2023-05-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_rename_forummessagereadby_topicmessagereadby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementuser',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='announcementuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='AnnouncementUser',
        ),
    ]
