# Generated by Django 4.2.1 on 2023-05-29 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0035_academicyear_alter_course_academic_year_and_more'),
        ('forums', '0005_remove_announcementuser_announcement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='status',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='title',
        ),
        migrations.AlterField(
            model_name='forum',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums', to='academic.course'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
