# Generated by Django 4.1 on 2023-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_remove_forum_end_date_remove_forum_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
