# Generated by Django 4.1 on 2023-05-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_remove_forum_end_date_remove_forum_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('HIDDEN', 'Hidden')], default='OPEN', max_length=32),
        ),
    ]
