# Generated by Django 4.1 on 2023-05-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_alter_forum_description_alter_forumtopic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmessage',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
