# Generated by Django 4.1 on 2023-05-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_alter_forumtopic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
