# Generated by Django 4.1 on 2023-05-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_alter_forumtopic_end_date_and_more'),
        ('forums', '0011_alter_topicmessage_previous_version_and_more'),
    ]

    operations = [
    ]
