# Generated by Django 4.1 on 2023-05-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0012_merge_20230530_1213'),
        ('forums', '0012_merge_20230530_1554'),
    ]

    operations = [
    ]
