# Generated by Django 4.2.1 on 2023-06-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0037_academicyear_name'),
        ('forums', '0012_merge_20230530_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum', to='academic.course'),
        ),
    ]
