# Generated by Django 4.2.1 on 2023-06-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0013_alter_forum_course'),
        ('forums', '0013_merge_20230531_0846'),
    ]

    operations = [
    ]
