# Generated by Django 4.2.1 on 2023-06-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0014_merge_20230601_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
