# Generated by Django 4.1 on 2023-06-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0014_merge_20230601_1055'),
        ('forums', '0015_alter_forumtopic_end_date'),
    ]

    operations = [
    ]
