# Generated by Django 4.1 on 2023-06-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0014_merge_20230601_1058'),
        ('forums', '0016_merge_20230601_1522'),
    ]

    operations = [
    ]
