# Generated by Django 4.2.1 on 2023-06-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0017_merge_20230605_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmessagereadby',
            name='text',
        ),
        migrations.RemoveField(
            model_name='topicmessagereadby',
            name='type',
        ),
    ]
