# Generated by Django 4.2.1 on 2023-06-20 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0019_alter_topicmessage_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='last_interaction',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
