# Generated by Django 4.2.1 on 2023-06-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_attachment_message_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='label',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
