# Generated by Django 4.2.1 on 2023-07-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='handle',
        ),
    ]
