# Generated by Django 4.2.1 on 2023-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_message_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
