# Generated by Django 4.2.1 on 2023-07-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readroommessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='readroommessage',
            name='user',
        ),
        migrations.AddField(
            model_name='readroommessage',
            name='user_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='read_room_messages', to='chats.userroom'),
        ),
        migrations.AddField(
            model_name='userroom',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
    ]
