# Generated by Django 4.2.1 on 2023-08-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_message_created_by_alter_message_lesson_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readroommessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_room_messages', to='chats.message'),
        ),
        migrations.AlterField(
            model_name='readroommessage',
            name='user_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_room_messages', to='chats.userroom'),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chatroom', to='chats.room'),
        ),
    ]
