# Generated by Django 4.1 on 2023-05-04 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0002_resource_lesson_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('content', models.CharField(max_length=512)),
                ('reference', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('NOT_APPROVED', 'Not Approved'), ('PENDING', 'Pending')], max_length=32)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_entry', to='databank.dataentry')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_entry', to='academic.program')),
            ],
        ),
    ]
