# Generated by Django 4.2.1 on 2023-05-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programentry',
            old_name='entry_id',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='programentry',
            old_name='program_id',
            new_name='program',
        ),
    ]
