# Generated by Django 4.2.1 on 2023-05-16 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databank', '0002_rename_entry_id_programentry_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='approved_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='reference',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('NOT_APPROVED', 'Not Approved'), ('PENDING', 'Pending')], max_length=32),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
