# Generated by Django 4.2.1 on 2023-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0006_alter_dataentry_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='programentry',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='programentry',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
