# Generated by Django 4.2.1 on 2023-06-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0007_programentry_description_programentry_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='reference',
            new_name='url',
        ),
    ]
