# Generated by Django 4.2 on 2023-04-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0004_alter_user_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('address', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=32)),
                ('branch', models.IntegerField(choices=[('CCS', 'Caracas'), ('MCB', 'Maracaibo'), ('PLC', 'Puerto la Cruz')])),
                ('programs', models.ManyToManyField(null=True, related_name='employees', to='academic.program')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_id', to='users.employee'),
        ),
    ]
