# Generated by Django 4.2 on 2023-04-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_resource_lesson_resources'),
        ('users', '0007_teacher_user_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='academic.course'),
        ),
    ]
