# Generated by Django 4.1 on 2023-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_teacher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.CharField(choices=[('CCS', 'Caracas'), ('MCB', 'Maracaibo'), ('PLC', 'Puerto la Cruz')], max_length=64),
        ),
    ]
