# Generated by Django 4.2.1 on 2023-05-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_employee_id_alter_user_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('academic_coordination', 'Coordinación Académica'), ('academy_coordination', 'Coordinación de Academia'), ('directors', 'Dirección'), ('external_coordinator', 'Coordinador Externo'), ('external_teacher', 'Docente Externo'), ('internal_teacher', 'Docente Interno'), ('IT', 'IT'), ('monitoring_coordinator', 'Coordinador de Seguimiento'), ('monitoring_teacher', 'Docente de Seguimiento'), ('post_sales', 'Post Ventas'), ('purchases_and_inventory', 'Procura y Administracion')], max_length=32, null=True),
        ),
    ]
