# Generated by Django 4.2.1 on 2023-05-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_teacher_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employee_id',
            new_name='employee_profile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='teacher_id',
            new_name='teacher_profile',
        ),
        migrations.DeleteModel(
            name='IT',
        ),
    ]
