# Generated by Django 4.2.1 on 2023-05-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_teacher_course_teacher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.teacher'),
        ),
    ]
