# Generated by Django 4.2.1 on 2023-05-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_employee_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
    ]
