# Generated by Django 4.2.1 on 2023-08-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_employee_programs_remove_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(choices=[('Internal', 'Interno'), ('External', 'Externo')], default='External', max_length=16),
        ),
    ]
