# Generated by Django 4.2 on 2023-04-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lic', models.CharField(max_length=255)),
                ('materials', models.CharField(max_length=255)),
                ('distributor', models.CharField(max_length=45)),
                ('n_lessons', models.IntegerField()),
                ('course_outline', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_subject', models.CharField(max_length=45)),
                ('learning_topic', models.CharField(max_length=45)),
                ('lesson_goal', models.CharField(max_length=45)),
                ('learning_outcomes', models.CharField(max_length=45)),
                ('generating_topic', models.CharField(max_length=45)),
                ('theoric_references', models.CharField(max_length=45)),
                ('curriculum_content', models.CharField(max_length=45)),
                ('beginning', models.CharField(max_length=45)),
                ('development', models.CharField(max_length=45)),
                ('closure', models.CharField(max_length=45)),
                ('script', models.URLField()),
                ('slides', models.URLField()),
                ('achievement_indicators', models.CharField(max_length=45)),
                ('main_activities', models.CharField(max_length=45)),
                ('program', models.ManyToManyField(related_name='lessons', to='academic.program')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_level_id', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.SmallIntegerField()),
                ('group_numbers', models.IntegerField()),
                ('trial', models.BooleanField(default=False)),
                ('program_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.program')),
            ],
        ),
    ]
