# Generated by Django 4.2.1 on 2023-05-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_resource_lesson_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='planification_term1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='planification_term2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='planification_term3',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='course_outline',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='distributor',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='program',
            name='materials',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='n_lessons',
            field=models.IntegerField(blank=True),
        ),
    ]
