# Generated by Django 4.2.1 on 2023-05-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_program_planification_term1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='program_id',
            new_name='program',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Creado'), (2, 'Suspendido'), (3, 'Activo'), (4, 'Inactivo'), (5, 'Finalizado')]),
        ),
    ]
