# Generated by Django 4.2.1 on 2023-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_rename_program_id_course_program_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group_numbers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Creado'), (2, 'Suspendido'), (3, 'Activo'), (4, 'Inactivo'), (5, 'Finalizado')], default=1),
        ),
    ]
