# Generated by Django 4.2.1 on 2023-05-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_resource_file_alter_resource_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course_block',
            new_name='CourseBlock',
        ),
    ]
