# Generated by Django 4.2.1 on 2023-05-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_program_course_outline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='script',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slides',
            field=models.URLField(blank=True),
        ),
    ]
