# Generated by Django 4.2.1 on 2023-05-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_lesson_script_alter_lesson_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='resource_of', to='academic.resource'),
        ),
    ]
