# Generated by Django 4.2.1 on 2023-05-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_alter_lesson_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='academic.program'),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_lesson', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='academic.course')),
            ],
        ),
    ]
