# Generated by Django 4.2.1 on 2023-05-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_remove_lesson_program_lessonprogram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonprogram',
            old_name='lesson_numer',
            new_name='lesson_number',
        ),
    ]
