# Generated by Django 4.2.1 on 2023-05-17 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_institutionlevel_logo'),
        ('users', '0018_remove_employee_programs_remove_teacher_course'),
        ('academic', '0013_rename_lesson_numer_lessonprogram_lesson_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='institution_level_id',
        ),
        migrations.AddField(
            model_name='course',
            name='institution_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='institutions.institutionlevel'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(related_name='courses', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='licens',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reference_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='employees',
            field=models.ManyToManyField(related_name='programs', to='users.employee'),
        ),
    ]
