# Generated by Django 4.2.1 on 2023-05-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_alter_course_status_alter_lesson_licens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('SUSPENDED', 'Suspendido'), ('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('FINISHED', 'Finalizado')], default='CREATED', max_length=16),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='achievement_indicators',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='beginning',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='closure',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='curriculum_content',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='development',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='generating_topic',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learning_outcomes',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learning_subject',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learning_topic',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_goal',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='main_activities',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theoric_references',
            field=models.CharField(max_length=512),
        ),
    ]
