# Generated by Django 4.2.1 on 2023-05-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_alter_course_teacher_alter_program_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogram',
            name='term',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='lessonprogram',
            name='lesson_number',
            field=models.IntegerField(blank=True, choices=[(1, 'Primer Lapso'), (2, 'Segundo Lapso'), (3, 'Tercer Lapso')], default=-1),
        ),
    ]
