# Generated by Django 4.2.1 on 2023-05-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_lessonprogram_term_alter_lessonprogram_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogram',
            name='lesson_number',
            field=models.IntegerField(choices=[(1, 'Primer Lapso'), (2, 'Segundo Lapso'), (3, 'Tercer Lapso')], default=-1),
        ),
    ]
