# Generated by Django 4.1 on 2023-05-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_alter_lessonprogram_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='achievement_indicators',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='beginning',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='closure',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='curriculum_content',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='development',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='generating_topic',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learning_outcomes',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learning_subject',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learning_topic',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_goal',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='main_activities',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='reference_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='resources',
            field=models.ManyToManyField(blank=True, null=True, related_name='resource_of', to='academic.resource'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='script',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slides',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theoric_references',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
