# Generated by Django 4.2.1 on 2023-05-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_alter_program_course_outline_alter_program_n_lessons_and_more'),
        ('academic', '0023_scholaryear_remove_course_end_date_and_more'),
    ]

    operations = [
    ]
