# Generated by Django 4.2.1 on 2023-05-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_merge_20230523_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='scholar_year',
        ),
    ]
