# Generated by Django 4.2.1 on 2023-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0027_alter_program_n_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_curricular',
            field=models.BooleanField(default=True),
        ),
    ]
