# Generated by Django 4.2.1 on 2023-05-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0028_course_is_curricular'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholaryear',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
