# Generated by Django 4.2.1 on 2023-05-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0029_scholaryear_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='academic_year',
        ),
        migrations.DeleteModel(
            name='ScholarYear',
        ),
    ]
