# Generated by Django 4.2.1 on 2023-05-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_scholaryear_course_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholaryear',
            name='name',
            field=models.CharField(max_length=32, default='prueba'),
        ),
    ]
