# Generated by Django 4.1 on 2023-05-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0033_remove_scholaryear_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
