# Generated by Django 4.1 on 2023-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0036_rename_academic_year_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
