# Generated by Django 4.2.1 on 2023-06-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0037_academicyear_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
