# Generated by Django 4.2.1 on 2023-06-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0038_rename_teacher_course_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='n_lessons',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
