# Generated by Django 4.2.1 on 2023-06-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0039_alter_program_n_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='next_lesson',
        ),
    ]
