# Generated by Django 4.2.1 on 2023-06-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0040_remove_coursesection_next_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='materials',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
