# Generated by Django 4.2.1 on 2023-06-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0041_alter_program_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='generating_topic',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='learning_outcomes',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='theoric_references',
        ),
        migrations.CreateModel(
            name='TPReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='theoric_references', to='academic.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('to_reference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='themes', to='academic.tpreference')),
            ],
        ),
        migrations.CreateModel(
            name='PreschoolObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='objectives', to='academic.learningoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='objectives', to='academic.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenss', to='academic.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='learning_outcomes', to='academic.lesson'),
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('components', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='learning_areas', to='academic.component')),
                ('generating_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='learning_areas', to='academic.generatingtopic')),
            ],
        ),
        migrations.AddField(
            model_name='generatingtopic',
            name='themes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='generating_topics', to='academic.theme'),
        ),
        migrations.CreateModel(
            name='CurricularContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='curricular_content', to='academic.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='curricular_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='components', to='academic.curricularcontent'),
        ),
        migrations.AddField(
            model_name='component',
            name='objectives',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='components', to='academic.preschoolobjective'),
        ),
        migrations.CreateModel(
            name='AchievementIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('licenss', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='achievement_indicator', to='academic.license')),
            ],
        ),
    ]
