# Generated by Django 4.2.1 on 2023-06-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0042_component_generatingtopic_learningoutcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='curricular_content',
        ),
        migrations.RemoveField(
            model_name='component',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='generatingtopic',
            name='themes',
        ),
        migrations.RemoveField(
            model_name='learningarea',
            name='components',
        ),
        migrations.RemoveField(
            model_name='learningarea',
            name='generating_topic',
        ),
        migrations.RemoveField(
            model_name='preschoolobjective',
            name='learning_outcome',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='to_reference',
        ),
        migrations.AddField(
            model_name='component',
            name='learning_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='components', to='academic.learningarea'),
        ),
        migrations.AddField(
            model_name='curricularcontent',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='curricular_content', to='academic.component'),
        ),
        migrations.AddField(
            model_name='generatingtopic',
            name='learning_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='generating_topics', to='academic.learningarea'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='objective', to='academic.preschoolobjective'),
        ),
        migrations.AddField(
            model_name='preschoolobjective',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preeschool_objectives', to='academic.component'),
        ),
        migrations.AddField(
            model_name='theme',
            name='generating_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='themes', to='academic.generatingtopic'),
        ),
        migrations.AddField(
            model_name='tpreference',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theoric_references', to='academic.theme'),
        ),
        migrations.AlterField(
            model_name='achievementindicator',
            name='licenss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='achievement_indicator', to='academic.license'),
        ),
        migrations.AlterField(
            model_name='curricularcontent',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='curricular_content', to='academic.lesson'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='learning_outcomes', to='academic.lesson'),
        ),
        migrations.AlterField(
            model_name='license',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenss', to='academic.lesson'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='objectives', to='academic.lesson'),
        ),
        migrations.AlterField(
            model_name='tpreference',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theoric_references', to='academic.lesson'),
        ),
    ]
