# Generated by Django 4.2.1 on 2023-06-26 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0043_remove_component_curricular_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='license',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='licens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons', to='academic.license'),
        ),
        migrations.DeleteModel(
            name='Objective',
        ),
        migrations.AddField(
            model_name='goal',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goals', to='academic.lesson'),
        ),
    ]
