# Generated by Django 4.2.1 on 2023-06-26 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0044_goal_remove_license_lesson_alter_lesson_licens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PreschoolGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preeschool_goals', to='academic.learningtopic')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='component',
            name='learning_area',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='generating_topic',
        ),
        migrations.RenameField(
            model_name='generatingtopic',
            old_name='learning_area',
            new_name='learning_subject',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='learning_subject',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='learning_topic',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_goal',
        ),
        migrations.RemoveField(
            model_name='tpreference',
            name='theme',
        ),
        migrations.RenameModel(
            old_name='LearningArea',
            new_name='LearningSubject',
        ),
        migrations.DeleteModel(
            name='PreschoolObjective',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddField(
            model_name='topic',
            name='generating_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topics', to='academic.generatingtopic'),
        ),
        migrations.AddField(
            model_name='learningtopic',
            name='learning_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='learning_topics', to='academic.learningsubject'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goal', to='academic.preschoolgoal'),
        ),
        migrations.AddField(
            model_name='tpreference',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theoric_references', to='academic.topic'),
        ),
        migrations.AlterField(
            model_name='curricularcontent',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='curricular_content', to='academic.learningtopic'),
        ),
        migrations.DeleteModel(
            name='Component',
        ),
    ]
