# Generated by Django 4.2.1 on 2023-06-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0046_learningsubject_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='lic',
        ),
        migrations.AddField(
            model_name='program',
            name='lic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programs', to='academic.license'),
        ),
        
    ]
