# Generated by Django 4.2.1 on 2023-06-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0048_rename_lic_program_licenss'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='recomended_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stage',
            field=models.CharField(blank=True, choices=[('Bachillerato', 'Bachillerato'), ('Primaria Menor', 'Primaria Menor'), ('Primaria Mayor', 'Primaria Mayor'), ('Preescolar', 'Preescolar')], max_length=32),
        ),
    ]
