# Generated by Django 4.2.1 on 2023-06-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0049_lesson_recomended_year_lesson_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='content',
            new_name='name',
        ),
    ]
