# Generated by Django 4.2.1 on 2023-06-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0050_rename_content_license_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Lunes'), ('TUESDAY', 'Martes'), ('WEDNESDAY', 'Miercoles'), ('THURSDAY', 'Jueves'), ('FRIDAY', 'Viernes')], max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule', to='academic.coursesection')),
            ],
        ),
    ]
