# Generated by Django 4.2.1 on 2023-08-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0054_lessonprogram_next_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='next_lesson',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.lessonprogram'),
        ),
    ]
