# Generated by Django 4.2.1 on 2023-08-09 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0056_alter_lessonprogram_next_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementindicator',
            name='licenss',
        ),
        migrations.RemoveField(
            model_name='program',
            name='materials',
        ),
        migrations.AddField(
            model_name='achievementindicator',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='achievement_indicator', to='academic.lesson'),
        ),
        migrations.CreateModel(
            name='ClassMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('optional', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academic.lesson')),
            ],
        ),
    ]
