# Generated by Django 4.2.1 on 2023-08-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0057_remove_achievementindicator_licenss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curricularcontent',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curricular_content', to='academic.learningtopic'),
        ),
        migrations.AlterField(
            model_name='curricularcontent',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curricular_content', to='academic.lesson'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='academic.preschoolgoal'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='academic.lesson'),
        ),
        migrations.AlterField(
            model_name='learningtopic',
            name='learning_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_topics', to='academic.learningsubject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='preschoolgoal',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preeschool_goals', to='academic.learningtopic'),
        ),
    ]
