# Generated by Django 4.2.1 on 2023-08-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0059_alter_lessonprogram_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementindicator',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievement_indicator', to='academic.lesson'),
        ),
        migrations.AlterField(
            model_name='generatingtopic',
            name='learning_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generating_topics', to='academic.learningsubject'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='academic.lesson'),
        ),
        migrations.AlterField(
            model_name='learningsubject',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_subject', to='academic.lesson'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='generating_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academic.generatingtopic'),
        ),
        migrations.AlterField(
            model_name='tpreference',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theoric_references', to='academic.lesson'),
        ),
        migrations.AlterField(
            model_name='tpreference',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theoric_references', to='academic.topic'),
        ),
    ]
