# Generated by Django 4.2.1 on 2023-08-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0060_alter_achievementindicator_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmaterial',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='materials', to='academic.classmaterial'),
        ),
    ]
