# Generated by Django 4.2.1 on 2023-08-10 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0061_remove_classmaterial_lesson_lesson_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='curriculum_content',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='licens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='academic.license'),
        ),
    ]
