# Generated by Django 4.2.1 on 2023-08-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0062_remove_lesson_curriculum_content_alter_lesson_licens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='academic.preschoolgoal'),
        ),
    ]
