# Generated by Django 4.2.1 on 2023-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0063_alter_learningoutcome_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='activity_guide',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='program',
            name='inventory',
            field=models.URLField(default=''),
        ),
    ]
