# Generated by Django 4.2.1 on 2023-08-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0065_classschedule_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseBlock',
        ),
    ]
