# Generated by Django 4.1 on 2023-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0066_delete_courseblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningoutcome',
            name='lesson',
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='lesson',
            field=models.ManyToManyField(blank=True, null=True, related_name='learning_outcomes', to='academic.lesson'),
        ),
    ]
