# Generated by Django 4.1 on 2023-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0069_remove_curricularcontent_lesson_remove_goal_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='program',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
