# Generated by Django 4.1 on 2023-08-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0076_lesson_lesson_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
