# Generated by Django 4.1 on 2023-08-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0077_alter_resource_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='distributor',
            new_name='description',
        ),
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='ES', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='short',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='version',
            field=models.CharField(default='ES', max_length=8),
            preserve_default=False,
        ),
    ]
