# Generated by Django 4.1 on 2023-08-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0078_rename_distributor_program_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='language',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Ingles')], default='ES', max_length=8),
        ),
        migrations.AlterField(
            model_name='program',
            name='version',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=8),
        ),
    ]
