# Generated by Django 4.1 on 2023-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcementuser',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('UNREAD', 'No leido'), ('READ', 'Leido'), ('EXPIRED', 'Expirado')], default='CREATED', max_length=45),
        ),
    ]
