# Generated by Django 4.2.1 on 2023-05-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_formquestion_formtemplate_teacherform_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormQuestionOptions',
            new_name='FormQuestionOption',
        ),
    ]
