# Generated by Django 4.2.1 on 2023-05-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_rename_formquestionoptions_formquestionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementuser',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
