# Generated by Django 4.2.1 on 2023-06-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0019_alter_institutioncoordinator_stage_and_more'),
        ('users', '0018_remove_employee_programs_remove_teacher_course'),
        ('monitoring', '0006_announcementuser_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='teacherform',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='teacher_surveys', to='institutions.institution'),
        ),
        migrations.CreateModel(
            name='TeacherFormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.CharField(max_length=1024)),
                ('form_template', models.ManyToManyField(
                    related_name='teacher_form_answers', to='monitoring.formtemplate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 related_name='teacher_answers', to='monitoring.formquestion')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 related_name='teacher_form_answers', to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 related_name='form_template', to='monitoring.formquestion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 related_name='form_questions', to='monitoring.formtemplate')),
            ],
        ),
    ]
