# Generated by Django 4.2.1 on 2023-06-05 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_formtemplate_name_teacherform_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='form_type',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Employee', 'Employee')], max_length=64),
        ),
        migrations.RemoveField(
            model_name='teacherformanswer',
            name='form_template',
        ),
        migrations.AlterField(
            model_name='teacherformanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_answers', to='monitoring.formquestion'),
        ),
        migrations.AddField(
            model_name='teacherformanswer',
            name='form_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_form', to='monitoring.teacherform'),
        ),
    ]
