# Generated by Django 4.2.1 on 2023-06-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_formquestion_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherformanswer',
            name='form_template',
        ),
        migrations.AlterField(
            model_name='teacherformanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_answers', to='monitoring.formquestion'),
        ),
        migrations.AddField(
            model_name='teacherformanswer',
            name='form_template',
            field=models.ManyToManyField(related_name='teacher_form_answers', to='monitoring.formtemplate'),
        ),
    ]
