# Generated by Django 4.2.1 on 2023-06-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_remove_teacherformanswer_form_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='status',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Creado', 'Creador')], default='Borrador', max_length=128),
        ),
    ]
