# Generated by Django 4.2.1 on 2023-06-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_alter_teacherform_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherformanswer',
            name='form_template',
        ),
        migrations.AddField(
            model_name='teacherformanswer',
            name='form_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_form_answers', to='monitoring.formtemplate'),
        ),
    ]
