# Generated by Django 4.1 on 2023-06-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0021_alter_institution_teachers'),
        ('monitoring', '0013_remove_teacherformanswer_form_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementuser',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_user', to='institutions.institution'),
        ),
    ]
