# Generated by Django 4.2.1 on 2023-06-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0038_rename_teacher_course_teachers'),
        ('monitoring', '0016_daytoday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_journal', to='academic.lesson')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_journal', to='academic.coursesection')),
            ],
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='options',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Multiple')], default=None, null=True),
        ),
        migrations.DeleteModel(
            name='DayToDay',
        ),
    ]
