# Generated by Django 4.2.1 on 2023-06-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_classjournal_alter_formquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='options',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Multiple')], default=1, null=True),
        ),
    ]
