# Generated by Django 4.1 on 2023-07-04 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_rename_current_lesson_classjournal_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplatequestion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_questions', to='monitoring.formtemplate'),
        ),
    ]
