# Generated by Django 4.1 on 2023-07-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_alter_formtemplatequestion_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='status',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Enviado', 'Enviado')], default='Borrador', max_length=128),
        ),
    ]
