# Generated by Django 4.1 on 2023-07-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_alter_formtemplate_status'),
        ('monitoring', '0024_remove_userformanswer_teacher_userformanswer_user_and_more'),
    ]

    operations = [
    ]
