# Generated by Django 4.2.1 on 2023-07-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_remove_userformanswer_teacher_userformanswer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userformanswer',
            name='form_template',
        ),
        migrations.RemoveField(
            model_name='userformanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='userformanswer',
            name='user_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='monitoring.userform'),
        ),
    ]
