# Generated by Django 4.2.1 on 2023-07-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_alter_formtemplate_status'),
        ('monitoring', '0025_remove_userformanswer_form_template_and_more'),
    ]

    operations = [
    ]
