# Generated by Django 4.1 on 2023-07-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_merge_20230706_1201'),
        ('monitoring', '0026_merge_20230706_1238'),
    ]

    operations = [
    ]
