# Generated by Django 4.2.1 on 2023-08-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0059_alter_lessonprogram_lesson_and_more'),
        ('monitoring', '0030_alter_classjournal_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classjournal',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_journal', to='academic.lesson'),
        ),
    ]
