# Generated by Django 4.2.1 on 2023-08-15 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0066_delete_courseblock'),
        ('monitoring', '0031_alter_classjournal_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('important', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=512)),
                ('answer', models.ManyToManyField(related_name='answers', to='monitoring.surveyanswer')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=512)),
                ('grade', models.IntegerField(default=0)),
                ('teacher_type', models.CharField(choices=[('Internal', 'Interno'), ('External', 'Externo')], max_length=32)),
                ('feedback', models.CharField(max_length=512)),
                ('reviewed', models.BooleanField(default=False)),
                ('course_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='academic.coursesection')),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_surveys', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
