# Generated by Django 4.2.1 on 2023-08-16 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0025_alter_institution_monitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0066_delete_courseblock'),
        ('monitoring', '0032_surveyanswer_surveyquestion_monitoringsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=512)),
                ('grade', models.IntegerField(default=0)),
                ('teacher_type', models.CharField(choices=[('Internal', 'Interno'), ('External', 'Externo')], max_length=32)),
                ('feedback', models.CharField(max_length=512)),
                ('reviewed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('course_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='academic.coursesection')),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_forms', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringFormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('important', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer',
        ),
        migrations.AlterField(
            model_name='userform',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_Forms', to='institutions.institution'),
        ),
        migrations.DeleteModel(
            name='MonitoringSurvey',
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
        migrations.AddField(
            model_name='monitoringformanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='monitoring.monitoringformquestion'),
        ),
        migrations.AddField(
            model_name='monitoringformanswer',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_forms_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
