# Generated by Django 4.2.1 on 2023-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0033_monitoringform_monitoringformanswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringformquestion',
            name='comment',
        ),
        migrations.AddField(
            model_name='monitoringformanswer',
            name='comment',
            field=models.CharField(default='', max_length=512),
        ),
    ]
