# Generated by Django 4.2.1 on 2023-08-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0034_remove_monitoringformquestion_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='monitoringformanswer',
            name='teacher',
        ),
        migrations.AddField(
            model_name='monitoringformanswer',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='monitoring.monitoringform'),
        ),
        migrations.AddField(
            model_name='monitoringformquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
