# Generated by Django 4.2.1 on 2023-08-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0035_training_remove_monitoringformanswer_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringformanswer',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='monitoring.monitoringform'),
        ),
    ]
