# Generated by Django 4.2.1 on 2023-08-16 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0066_delete_courseblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0036_alter_monitoringformanswer_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringform',
            name='estimated_grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoringformanswer',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoringformanswer',
            name='mandatory_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoringformquestion',
            name='area',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='monitoringformquestion',
            name='type',
            field=models.CharField(blank=True, choices=[('Internal', 'Interno'), ('External', 'Externo')], max_length=32),
        ),
        migrations.AddField(
            model_name='monitoringformquestion',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='programs',
            field=models.ManyToManyField(related_name='trainings', to='academic.program'),
        ),
        migrations.AddField(
            model_name='training',
            name='stage',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='task_info',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='training',
            name='teachers',
            field=models.ManyToManyField(related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=1024)),
                ('date', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_training_tasks', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_tasks', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='monitoring.training')),
            ],
        ),
    ]
