# Generated by Django 4.2.1 on 2023-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0037_monitoringform_estimated_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringformanswer',
            name='mandatory_comment',
        ),
        migrations.AddField(
            model_name='monitoringformquestion',
            name='mandatory_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitoringformquestion',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
