# Generated by Django 4.2.1 on 2023-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0040_alter_monitoringform_estimated_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtask',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
