# Generated by Django 4.2.1 on 2023-08-23 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0027_alter_institution_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0042_remove_monitoringformanswer_important_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='monitoring.formtemplate'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_Forms', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
