# Generated by Django 4.2.1 on 2023-08-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0043_alter_userform_form_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformanswer',
            name='user_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='monitoring.userform'),
        ),
    ]
