# Generated by Django 4.2.1 on 2023-08-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0044_alter_userformanswer_user_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringformanswer',
            name='not_applies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoringformquestion',
            name='dependent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.monitoringformquestion'),
        ),
    ]
