# Generated by Django 4.2.1 on 2023-08-24 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0045_monitoringformanswer_not_applies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtask',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='trainingtask',
            name='grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trainingtask',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_training_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
