# Generated by Django 4.2.1 on 2023-08-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0046_alter_trainingtask_comment_alter_trainingtask_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtask',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
