# Generated by Django 4.2.1 on 2023-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0047_alter_trainingtask_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtask',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
