# Generated by Django 4.1 on 2023-02-23 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('classrooms_per_level', models.PositiveIntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('students_per_classwoom', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('ocupancy_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('teacher_service', models.CharField(choices=[('INT', 'Internal'), ('EXT', 'External'), ('MIX', 'Mixed')], max_length=20)),
                ('monitor_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
