# Generated by Django 4.1 on 2023-02-23 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_institution_classrooms_per_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='classrooms_per_level',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='ocupancy_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='students_per_classwoom',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
