# Generated by Django 4.1 on 2023-02-23 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0003_alter_institution_classrooms_per_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='monitor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
