# Generated by Django 4.2 on 2023-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_teacher_user_teacher_id'),
        ('institutions', '0004_alter_institution_monitor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='teachers',
            field=models.ManyToManyField(related_name='institution', to='users.teacher'),
        ),
    ]
