# Generated by Django 4.2.1 on 2023-05-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_institution_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='students_per_classwoom',
            new_name='students_per_classroom',
        ),
    ]
