# Generated by Django 4.2.1 on 2023-05-16 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0007_rename_monitor_id_institution_monitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='institution_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45)),
                ('stage', models.CharField(blank=True, max_length=45)),
                ('reference_level', models.CharField(blank=True, max_length=45)),
                ('student_sections', models.IntegerField(blank=True)),
                ('students_per_section', models.IntegerField(blank=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_levels', to='institutions.institution')),
                ('institution_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
