# Generated by Django 4.2.1 on 2023-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_rename_institution_level_institutionlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionlevel',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
