# Generated by Django 4.2.1 on 2023-05-18 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0010_institutionlevel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=45)),
                ('institution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coordinator', to='institutions.institution')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coordinator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
