# Generated by Django 4.1 on 2023-05-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_institutioncoordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
