# Generated by Django 4.1 on 2023-05-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_institution_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionlevel',
            name='logo',
        ),
    ]
