# Generated by Django 4.1 on 2023-05-22 20:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0016_alter_institution_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
