# Generated by Django 4.2.1 on 2023-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0018_alter_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutioncoordinator',
            name='stage',
            field=models.CharField(blank=True, choices=[('Bachillerato', 'Bachillerato'), ('Primaria Menor', 'Primaria Menor'), ('Primaria Mayor', 'Primaria Mayor'), ('Preescolar', 'Preescolar')], max_length=45),
        ),
        migrations.AlterField(
            model_name='institutionlevel',
            name='stage',
            field=models.CharField(blank=True, choices=[('Bachillerato', 'Bachillerato'), ('Primaria Menor', 'Primaria Menor'), ('Primaria Mayor', 'Primaria Mayor'), ('Preescolar', 'Preescolar')], max_length=45),
        ),
    ]
