# Generated by Django 4.2.1 on 2023-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_employee_programs_remove_teacher_course'),
        ('institutions', '0019_alter_institutioncoordinator_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='institution', to='users.teacher'),
        ),
    ]
