# Generated by Django 4.1 on 2023-06-12 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0021_alter_institution_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='classrooms_per_level',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='students_per_classroom',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
