# Generated by Django 4.2.1 on 2023-06-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0022_alter_institution_classrooms_per_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionlevel',
            name='reference_level',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
