# Generated by Django 4.2.1 on 2023-06-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0023_alter_institutionlevel_reference_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionlevel',
            name='student_sections',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='institutionlevel',
            name='students_per_section',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
